using System;

namespace AbaAbilities.Core
{
    [Flags]
    public enum HookType : ulong
    {
        None = 0,
        ResetEffects = 1UL << 0,
        UpdateDead = 1UL << 1,
        PreUpdate = 1UL << 2,
        ProcessTriggers = 1UL << 3,
        SetControls = 1UL << 4,
        PreUpdateBuffs = 1UL << 5,
        PostUpdateBuffs = 1UL << 6,
        UpdateEquips = 1UL << 7,
        PostUpdateEquips = 1UL << 8,
        PostUpdateMiscEffects = 1UL << 9,
        PostUpdateRunSpeeds = 1UL << 10,
        PreUpdateMovement = 1UL << 11,
        PostUpdate = 1UL << 12,
        UpdateLifeRegen = 1UL << 13,
        UpdateBadLifeRegen = 1UL << 14,
        NaturalLifeRegen = 1UL << 15,
        FrameEffects = 1UL << 16,
        FreeDodge = 1UL << 17,
        ConsumableDodge = 1UL << 18,
        ModifyHurt = 1UL << 19,
        OnHurt = 1UL << 20,
        PostHurt = 1UL << 21,
        PreKill = 1UL << 22,
        Kill = 1UL << 23,
        ModifyHitByNPC = 1UL << 24,
        OnHitByNPC = 1UL << 25,
        ModifyHitByProjectile = 1UL << 26,
        OnHitByProjectile = 1UL << 27,
        CanHitNPC = 1UL << 28,
        ModifyHitNPC = 1UL << 29,
        OnHitNPC = 1UL << 30,
        CanHitNPCWithItem = 1UL << 31,
        ModifyHitNPCWithItem = 1UL << 32,
        OnHitNPCWithItem = 1UL << 33,
        CanHitNPCWithProj = 1UL << 34,
        ModifyHitNPCWithProj = 1UL << 35,
        OnHitNPCWithProj = 1UL << 36,
        CanHitPvp = 1UL << 37,
        CanHitPvpWithProj = 1UL << 38,
        OnHitAnything = 1UL << 39,
        PreItemCheck = 1UL << 40,
        PostItemCheck = 1UL << 41,
        UseTimeMultiplier = 1UL << 42,
        UseAnimationMultiplier = 1UL << 43,
        UseSpeedMultiplier = 1UL << 44,
        CanConsumeAmmo = 1UL << 45,
        OnConsumeAmmo = 1UL << 46,
        CanShoot = 1UL << 47,
        ModifyShootStats = 1UL << 48,
        Shoot = 1UL << 49,
        MeleeEffects = 1UL << 50,
        ModifyWeaponDamage = 1UL << 51,
        ModifyWeaponKnockback = 1UL << 52,
        ModifyWeaponCrit = 1UL << 53,
        GetHealLife = 1UL << 54,
        GetHealMana = 1UL << 55,
        ModifyManaCost = 1UL << 56,
        OnMissingMana = 1UL << 57,
        OnConsumeMana = 1UL << 58,
        ModifyMaxStats = 1UL << 59,
        WhileAttackKeyDown = 1UL << 60,
        OnAttackKeyUp = 1UL << 61,
        WhileUseKeyDown = 1UL << 62,
        OnUseKeyUp = 1UL << 63
    }
}
